config/routes.rb
Rails.application.routes.draw do
  resources :locations

  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  root 'welcome#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/email.rb
class Email < ActiveRecord::Base
  belongs_to :user
end

app/models/location.rb
class Location < ActiveRecord::Base
  validates :location_name, presence: true
  validates :address, presence: true
  geocoded_by :address
  after_validation :geocode
  belongs_to :user
end

app/models/phone.rb
class Phone < ActiveRecord::Base
  belongs_to :user
  validates :phone_number, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :locations
  has_one :phone
  accepts_nested_attributes_for :locations, allow_destroy: true
  accepts_nested_attributes_for :phone, allow_destroy: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concerns/webhookable.rb
module Webhookable
extend ActiveSupport::Concern
 
  def set_header
          response.headers["Content-Type"] = "text/xml"
  end
 
  def render_twiml(response)
          render text: response.text
  end
 
end

app/controllers/locations_controller.rb
require 'HTTParty'
require 'will_paginate/array'

class LocationsController < ApplicationController
  before_action :get_user
  before_action :get_passes, only: [:show]
  before_action :find_location, only: [:show, :edit, :update, :destroy]

  def index
    @locations = current_user.locations.paginate(page: params[:page], per_page: 10)
    @hash = Gmaps4rails.build_markers(@locations) do |location, marker|
      marker.lat location.latitude
      marker.lng location.longitude
    end
  end

  def find_location
    @location = Location.find(params[:id])
  end

  def show
    @location = Location.find(params[:id])
  end

  def new
    @location = Location.new
  end

  def create
    @location = Location.create location_params

    if @location.save
      redirect_to @location
    else
      render 'new'
    end
  end

  def update
    if @location.update(location_params)
      redirect_to @location
    else
      render 'edit'
    end
  end

  def destroy
    @location.destroy
    redirect_to locations_path, notice: "Successfully deleted locations."
  end

  def get_passes
    @location = Location.find(params[:id])
    @iss_passes = HTTParty.get("http://api.open-notify.org/iss-pass.json?lat=#{@location.latitude}&lon=#{@location.longitude}&n=50", :verify => false)["response"]
    @iss_passes = @iss_passes.paginate(page: params[:page], per_page: 10)
  end

  def get_user
    @user = current_user
  end

  private
  def location_params
    params.require(:location).permit(:location_name, :address, users_attributes: [:id, :email, :_destroy])
  end

end

app/controllers/twilio_controller.rb
require 'twilio-ruby'
 
class TwilioController < ApplicationController
  include Webhookable
 
  after_filter :set_header
 
  skip_before_action :verify_authenticity_token
 
  def voice
    response = Twilio::TwiML::Response.new do |r|
      r.Say 'Hey there. Congrats on integrating Twilio into your Rails 4 app.', :voice => 'alice'
         r.Play 'http://linode.rabasa.com/cantina.mp3'
    end
 
    render_twiml response
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  #before_filter :configure_permitted_parameters, only: [:create, :update]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def sign_up_params
    puts 'test'
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, phone_attributes: [:phone_number])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/welcome_controller.rb
require 'httparty'

class WelcomeController < ApplicationController
  before_action :get_location
  before_action :logged_in

  def logged_in
    if user_signed_in?
      @user = current_user
    end
  end
  def get_location
    iss_data = HTTParty.get("https://api.wheretheiss.at/v1/satellites/25544", :verify => false)
    mi_per_km = 0.621371
    @name = iss_data["name"]
    @id = iss_data["id"]
    @latitude = iss_data["latitude"]
    @longitude = iss_data["longitude"]
    @altitude = (iss_data["altitude"] * mi_per_km).round(2)
    @velocity = (iss_data["velocity"] * mi_per_km).round(2)
    @visibility = iss_data["visibility"]
    @footprint = iss_data["footprint"]
    @timestamp = Time.at(iss_data["timestamp"].to_i)
    @time = @timestamp.strftime('%H:%M:%S %p %Z')
    @daynum = iss_data["daynum"]
    @solar_lat = iss_data["solar_lat"]
    @solar_lon = iss_data["solar_lon"]
    @units = iss_data["units"]
    @iss_location = "#{iss_data['latitude']},#{iss_data['longitude']}"
  end

  def index
  end

  def about
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ISS App</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <button class="navbar-toggle collapsed" data-target="#navbar-items" data-toggle="collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "ISS App", root_path, class: "navbar-brand" %>
      </div>
      <div class="collapse navbar-collapse" id="navbar-items">
        <% if user_signed_in? %>
          <ul class="nav navbar-nav">
            <li><%= link_to "About" %></li>
            <li><%= link_to "My Passes" %></li>
            <li><%= link_to "My Notifications" %></li>
            <li><%= link_to "My Locations", locations_path %></li>
            <li class="dropdown">
              <a href="user" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= @user.first_name %> <%= @user.last_name %><span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                  <li><%= link_to "Locations", locations_path %></li>
                  <li><%= link_to "Notifications" %></li>
                  <li><%= link_to "Settings", edit_user_registration_path %></li>
                  <li><%= link_to "Log out", destroy_user_session_path, :method => :delete %></li>
                </ul>
            </li>
          </ul>
        <% else %>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Sign In", new_user_session_path %></li>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
          </ul>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>

  <div class="container">
    <%= yield %>
  </div> 
</html>

app/views/locations/_form.html.erb
<%= simple_nested_form_for @location do |f| %>
  
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@location.errors.count, "error") %> prevented this location from being saved:
        <!-- 'pluralize' is a rails helper that takes a number and a string as arguments. If the number is greater than one, the string is automatically pluralized. -->
      </h2>
      <ul>
        <% @location.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>



<!-- The 'url: locations_path' tells the form to 
submit to the locations POST route by default. The
'form_for :location' part tells rails that the form 
is for our 'articles' resource. -->
  <%= f.input :location_name %>
  <%= f.input :address, placeholder: "'123 Main Street Nashville' or 'New York City' or even just '20852'" %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/locations/create.html.erb
<h1>Locations#create</h1>
<p>Find me in app/views/locations/create.html.erb</p>

app/views/locations/destroy.html.erb
<h1>Locations#destroy</h1>
<p>Find me in app/views/locations/destroy.html.erb</p>

app/views/locations/edit.html.erb
<div class="page-header">
  <h1>Update Location</h1>
</div>

<%= render 'form' %>

<%= link_to "Back", locations_path %>

app/views/locations/index.html.erb
<p id="notice">
<div class="page-header">
  <h1>My Locations</h1>
</div>
<% if @locations.any? %>
  <table class="table table-striped">
    <thead>
      <th>Name</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="2">Actions</th>
    </thead>
    <%= will_paginate @locations, renderer: BootstrapPagination::Rails %>
      <% @locations.each do |location| %>
        <tr>
          <td><%= link_to location.location_name, location %></td>
          <td class="align-right"><%= location.latitude.round(7) %></td>
          <td><%= location.longitude.round(7) %></td>
          <td>
            <%= link_to 'Edit', edit_location_path(location) %>
          </td>
          <td>
            <%= link_to 'Delete', location_path(location), :method => :delete, :confirm => 'Are you sure?', :class => 'text-danger' %>
          </td>
        </tr>
      <% end %>
  </table>
<% else %>
  <p>You haven't created any locations yet. Click "Add a location" to get started.</p>
<% end %>
<br>
<%= link_to "Add a location", new_location_path, class: "btn btn-primary" %>

app/views/locations/new.html.erb
<h1>New Location</h1>

<%= render 'form' %><br>

<%= link_to "Back", root_path, class: "btn btn-default" %>

app/views/locations/show.html.erb
<div class="page-header">
  <h1><%= @location.location_name %></h1>
  <h3>Coordinates: <%= @location.latitude %>, <%= @location.longitude %></h3>
  <%= link_to "Edit", edit_location_path %>
</div>

<h2>Future Passes</h2>
<table class="table table-striped">
  <thead>
    <th>Date</th>
    <th>Time to Pass</th>
    <th>Duration</th>
    <th>Rise Time</th>
  </thead>
    <% @iss_passes.each do |pass| %>
      <tr>
        <td><%= Time.at(pass["risetime"].to_i).strftime('%A %B %e, %Y') %></td>
        <td><%= distance_of_time_in_words(Time.now, Time.at(pass["risetime"].to_i)) %></td>
        <td><%= Time.at(pass["duration"].to_i).strftime('%M') %>m <%= Time.at(pass["duration"].to_i).strftime('%S') %>s</td>
        <td><%= Time.at(pass["risetime"].to_i).strftime('%I:%M %P %Z') %></td>
      </tr>
    <% end %>
</table>
<%= will_paginate @iss_passes, renderer: BootstrapPagination::Rails %>

app/views/locations/update.html.erb
<h1>Locations#update</h1>
<p>Find me in app/views/locations/update.html.erb</p>

app/views/welcome/index.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" type="text/javascript"></script>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-3 col-md-offset-9">
      <div class="panel panel-default">
        <div class="table-responsive">
          <table class="table table-striped">
            <tbody>
              <tr>
                <td><strong>Time</strong></td>
                <td><%= @time %></td>
              </tr>
              <tr>
                <td><strong>Altitude</strong></td>
                <td><%= @altitude %> miles</td>
              </tr>
              <tr>
                <td><strong>Velocity</strong></td>
                <td><%= @velocity %> mph</td>
              </tr>
              <tr>
                <td><strong>Latitude</strong></td>
                <td><%= @latitude %></td>
              </tr>
              <tr>
                <td><strong>Longitude</strong></td>
                <td><%= @longitude %></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<div id="map"></div>

<script type="text/javascript">
function moveISS () {
    $.getJSON('http://api.open-notify.org/iss-now.json?callback=?', function(data) {
        var lat = data['iss_position']['latitude'];
        var lon = data['iss_position']['longitude'];

        // See leaflet docs for setting up icons and map layers
        // The update to the map is done here:
        iss.setLatLng([lat, lon]);
        isscirc.setLatLng([lat, lon]);
        map.panTo([lat, lon], animate=true);
    });
    setTimeout(moveISS, 1000); 
}


var map = handler = Gmaps.build('Google');
var latitude = <%= @latitude || 0 %>;
var longitude = <%= @longitude || 0 %>;
handler.buildMap({
  internal: {id: 'map'},
  provider: {
      zoom: 3,
      center: new google.maps.LatLng(latitude, longitude),
      styles: mapStyle
    }
  }, 
  function(){
  markers = handler.addMarkers([
    {
      "lat": latitude,
      "lng": longitude,
      /*"picture": {
        "url": "http://icon.softwaresea.com/32x32/5/394/1196603.891ea57c45143d46f175d87e8951cfb8.gif",
        "width":  36,
        "height": 36,
      },*/
      "infowindow": "hello!"
    },
  ]);
});
nite.init(map);
</script>